=== keerthimurali224/ShopEase-Online-Store/clothes.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="clothes">
    <xs:complexType>
      <xs:sequence>

        <xs:element name="product" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name" type="xs:string"/>
              <xs:element name="brand" type="xs:string"/>
              <xs:element name="price" type="xs:integer"/>
              <xs:element name="size" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== keerthimurali224/ShopEase-Online-Store/clothes.xml
<?xml version="1.0" encoding="UTF-8"?>

<clothes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="clothes.xsd">

    <product>
        <name>T-Shirt</name>
        <brand>Puma</brand>
        <price>500</price>
        <size>M</size>
    </product>

    <product>
        <name>Jeans</name>
        <brand>Levis</brand>
        <price>1200</price>
        <size>32</size>
    </product>

</clothes>
